---
- name: Avi Controller | GKE | Get controller addresses
  gcp_compute_address_facts:
    region: "{{ avi_gcp_region }}"
    project: "{{ avi_gcp_project }}"
    auth_kind: "{{ avi_gcp_auth_kind }}"
    service_account_file: "{{ avi_gcp_service_account_file }}"
    filters:
      - "name:{{ avi_controller_prefix }}-{{ avi_namespace }}*"
  register: avi_gcp_compute_address_facts
  when: avi_already_exists

- block:
    - name: Avi Controller | GKE | Suspend deplyoment | Set the primary cluster controller
      set_fact:
        avi_deployment_controller: "{{ avi_gcp_compute_address_facts.resources[0].address }}"

    - name: Avi Controller | GKE | Suspend deployment | Check if deployment is reachable
      uri:
        url: https://{{ avi_deployment_controller }}/api/initial-data
        method: GET
        return_content: yes
        validate_certs: no
      register: initial_data
      failed_when: false

    - name: Avi Controller | GKE | Suspend deployment | Verify no service engines exist
      avi_api_session:
        controller: "{{ avi_deployment_controller }}"
        username: "{{ avi_controller_username }}"
        avi_credentials:
          password: "{{ avi_controller_password }}"
        api_version: 17.2.13
        http_method: get
        tenant: "*"
        path: serviceengine
      register: serviceengine
      when:
        - initial_data.status == 200

    - name: Avi Controller | GKE | Suspend deployment | Verify no virtual services exist
      avi_api_session:
        controller: "{{ avi_deployment_controller }}"
        username: "{{ avi_controller_username }}"
        avi_credentials:
          password: "{{ avi_controller_password }}"
        api_version: 17.2.13
        http_method: get
        tenant: "*"
        path: virtualservice
      register: virtualservice
      when:
        - initial_data.status == 200

    - name: Avi Controller | GKE | Suspend deployment | Verify that no dependent objects exist
      assert:
        that:
          - virtualservice.obj.count == 0
          - serviceengine.obj.count == 0
  when:
    - avi_gcp_compute_address_facts.resources|length > 0
    - avi_controller_password is defined
    - avi_already_exists
